spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_app
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis

tmdb:
  api:
    base-url: https://api.themoviedb.org
    key: ${TMDB_API_KEY}